// /slots.ts
import api from "@/lib/api";

export enum SlotType {
  LD = "LD",
  JP = "JP",
}

export enum SlotStatus {
  OPEN = "OPEN",
  CLOSED = "CLOSED",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
}

export interface Slot {
  id: string;
  createdAt: string;
  updatedAt: string;
  uniqueSlotId: string;
  type: SlotType;
  slotTime: string;
  windowCloseAt: string;
  status: SlotStatus;
  isAutoGenerated?: boolean;
  settingsJson: Record<string, any> | null;
  totalUnits?: number; // ⭐ new
}

export interface ActiveSlotsResponse {
  slots: Slot[];
}

export interface CreateSlotResponse {
  id: string;
  uniqueSlotId: string;
  type: SlotType;
  slotTime: string;
  windowCloseAt: string;
  status: SlotStatus;
  settingsJson: Record<string, any> | null;
  createdAt: string;
  updatedAt: string;
  isAutoGenerated?: boolean;
}

export interface GenerateFutureSlotsResponse {
  message: string;
}

export interface GroupedSlot {
  id: string;
  uniqueSlotId: string;
  type: "LD" | "JP";
  slotTime: string; // UTC
  windowCloseAt: string;
  status: "OPEN" | "CLOSED" | "COMPLETED" | "CANCELLED";
  slotTimeMYT: string;
  slotTimeFormatted: string;
  settingsJson: {
    bidPrize: number;
    winningPrize: number;
  };
  winningNumber?: number; // Actual winning number after draw is completed
}

export const createSlot = async (payload: {
  type: SlotType;
  slotTime: string;
  settingsJson?: Record<string, any>;
}): Promise<CreateSlotResponse> => {
  const { data } = await api.post<CreateSlotResponse>("/slots", payload);
  return data;
};

export const updateSlot = async (
  id: string,
  payload: {
    slotTime?: string;
    status?: SlotStatus;
    settingsJson?: Record<string, any>;
  }
): Promise<Slot> => {
  const { data } = await api.patch<Slot>(`/slots/${id}`, payload);
  return data;
};

export const autoGenerateFutureSlots =
  async (): Promise<GenerateFutureSlotsResponse> => {
    const { data } = await api.post<GenerateFutureSlotsResponse>(
      "/slots/generate"
    );
    return data;
  };

export const getAllSlots = async () => {
  const res = await api.get("/slots/all");
  return res.data;
};

export const getActiveSlots = async (): Promise<Slot[]> => {
  const { data } = await api.get<Slot[]>("/slots/active");
  return data;
};

export const getSlotsGroupedByDate = async (): Promise<
  Record<string, GroupedSlot[]>
> => {
  const res = await api.get("/slots/grouped-by-date");
  return res.data;
};

export const getSlotSummary = async (slotId: string): Promise<any> => {
  const res = await api.get(`/bids/summary/${slotId}`);
  return res.data;
};
